### ISSUE TITLE
Remote connection sensor gives me unknown

### ISSUE THREAD

**Issue by greberg** [custom-components/remote_homeassistant#101]
Hi

Running 2020.12.1 release of HA on both instances. All my sensors updates fine between the instances but the remote connection sensor gives me unknown. This has been working before and no changes has been made except updating to remote_homeassistant 3.1. No error is report in debug mode 

2021-01-08 18:00:13 INFO (MainThread) [custom_components.remote_homeassistant] Connecting to ws://xx.x.x.xxx:8123/api/websocket
2021-01-08 18:00:13 INFO (MainThread) [custom_components.remote_homeassistant] Connected to home-assistant websocket at ws://xx.x.x.xxx:8123/api/websocket
2021-01-08 18:00:13 DEBUG (MainThread) [custom_components.remote_homeassistant] received: {'type': 'auth_required', 'ha_version': '2020.12.1'}
2021-01-08 18:00:13 DEBUG (MainThread) [custom_components.remote_homeassistant] received: {'type': 'auth_ok', 'ha_version': '2020.12.1'}

Any ideas?

**Comment by postlund** [comment]
Can you try `master` and see if it works better?

**Comment by greberg** [comment]
No success with master unfortunately.

**Comment by postlund** [comment]
Can you please try with latest version in HACS as well?

**Comment by greberg** [comment]
Works fine for me in 3.3 version

**Comment by greberg** [comment]
Stop working after updating HA 2021.3.3. Now it says unknown again

**Comment by greberg** [comment]
Yes it looks like it works if I restart the remote node. I have turned on debug as well so I will see if I can get you somme logs as well.

**Comment by postlund** [comment]
Yeah, then it's definitely the race condition I'm thinking of. The "connection object" sends events to the sensor when it changes state (e.g. gets connected), but during startup it might happen that a connection is made prior to the sensor being set up. So it misses the event. When you restart the remote node or if the connection is lost somehow, so a connection re-attempt is made, it will as work as the sensor has already been set up. I'll try to fix this later today or so.

**Comment by greberg** [comment]
Cool! Thanks for that

**Comment by postlund** [comment]
@greberg Can you try if #118 works better?

**Comment by greberg** [comment]
Yes, looks like it works now with the changes made in #118 Will report back to see it holds up as well.

**Comment by postlund** [comment]
Great! Let's leave it for a few day and then merge it in case it works well.

**Comment by greberg** [comment]
Can confirm it still works now after a couple of days. Even after restart and update of HA. Thanks a lot
