### ISSUE TITLE
HACS always shows as install , despite being installed

### ISSUE THREAD

**Issue by danmed** [custom-components/remote_homeassistant#102]
I've completely removed the manually installed version, and installed via HACS.. but HACS always shows it as installable.

![image](https://user-images.githubusercontent.com/3878490/104138637-30e1b000-539d-11eb-9e9a-6e0135a3a342.png)

![image](https://user-images.githubusercontent.com/3878490/104138641-3a6b1800-539d-11eb-9ec1-0a2a1ab8487c.png)

**Comment by dodg3r** [comment]
Same for me.

**Comment by lukas-hetzenecker** [comment]
duplicate of #97 
should hopefully be resolved soon with hacs/default#757

**Comment by PierreScerri** [comment]
I have this issue too.
The 'New Repository' keeps popping up whether I install or delete or dismiss it.
