### ISSUE TITLE
Listen to remote events

### ISSUE THREAD

**Issue by marc-romu** [custom-components/remote_homeassistant#103]
Is it possible to listen to events on a remote home assistant?

Thanks!

**Comment by postlund** [comment]
Yep, just add them to `subscribed_events` or the corresponding thing under Options if you set up via config flow.

**Comment by marc-romu** [comment]
Thanks! I don't know why I was expecting the event to start with the prefix configured in `entity_prefix`. But it has no sense because an event is not an entity 😅 . Solved, thanks!!
