### ISSUE TITLE
Documentation - where to install component

### ISSUE THREAD

**Issue by borpin** [custom-components/remote_homeassistant#105]
Could the documentation be explicit as to where the component is added. Is it added to the main instance or the instance designated the remote.

**Comment by ICuddlesI** [comment]
The main instance

**Comment by borpin** [comment]
Hi Yes, I'm aware of that, just suggesting the documentation was explicit on that 😀

**Comment by tsat-psv** [comment]
You can edit the `README.md` directly from the browser @borpin, and commit a PR from your changes. It's super easy and convenient now in github. I suggest you give that a go :)

**Comment by postlund** [comment]
Yes, feel free to send changes! 👍 Also feel free to change "master instance" to "main instance" instead.
