### ISSUE TITLE
Disable discovery introduced with #64

### ISSUE THREAD

**Issue by makuser** [custom-components/remote_homeassistant#107]
We need to be able to disable the remote instance discovery (#64).

![Bildschirmfoto von 2021-01-26 16-37-57](https://user-images.githubusercontent.com/1778889/105867046-ebf08700-5ff4-11eb-9eeb-bd5e0de8ff55.png)

Seeing this screen after an update is really not desired in my use case.

**Comment by postlund** [comment]
It's not much we can do about that as long as discovery is supported without possibly residing to ugly hacks. The way to fix this is requesting a feature to disable discovery per integration upstream in Home Assistant. Sounds like a valid feature to me.

**Comment by lukas-hetzenecker** [comment]
Closing this issue as "WONTFIX", as it is out of scope for remote_homeassistant - sorry for the spam in discovery, but there's really not a lot we can do about it
