### ISSUE TITLE
Manifest File needs updating for new version of HA

### ISSUE THREAD

**Issue by thorrrr** [custom-components/remote_homeassistant#112]
Please see Dev Blog [here ](https://www.home-assistant.io/blog/2021/03/03/release-20213/#breaking-changes)read first point

**Comment by lukas-hetzenecker** [comment]
The current master already contains the Manifest File with a version attribute - I'll create a new release now, so the latest released version does as well. - This will hopefully also speed up hacs/default#757 ...
