### ISSUE TITLE
How to filter only a few entities?

### ISSUE THREAD

**Issue by koffienl** [custom-components/remote_homeassistant#120]
How do you whitelist only a few entities?
this is my current config:

Basic Options (step 1/4)
Entity prefix: from_ha_remote

Domain and entity filters (step 2/4)
include domains: sensor, light, switch
include entities: selected a handful entities from the remote HA instance
exclude domains: empty
exclude entities: empty

Filters (step 3/4)
empty

Subscribed events (step 4/4)
empty

It works, but it will result in every single sensor, light or switch from the remote HA in the current HA, with a prefix 'from_ha_remote'

How to make the config to only whitelist a few entities and blocking everything else?

**Comment by postlund** [comment]
Remove the domain filters and just pick entities from the list?

**Comment by koffienl** [comment]
Jup, just found that one out ;)
I thought you had to select the domains and entities.
