### ISSUE TITLE
No remote entities added to integration

### ISSUE THREAD

**Issue by jlaitinen81** [custom-components/remote_homeassistant#121]
I'm trying to get some sensor's information from a remote HA to my main HA. I installed the Remote Home-Assistant from HACS and added the integration from Configuration.

Everything seems to install smoothly, but the only entity I can see under the Remote HA integration is the sensor.remote_connection_to_myhassio_duckdns_org_8123. This sensor shows the Remote connection status as connected, so no issues there either. I have not defined any filters, just a prefix for both the entities and sensors.

I can even see the remote entities in the "include entities" drop down on step 2/4, but as said nothing is added.

Something I am missing? Should the entities just automatically appear? I've tried restarting Hassio several times, but no help.

**Comment by postlund** [comment]
Yeah, they should appear automatically. Anything in the log?

**Comment by jlaitinen81** [comment]
Nothing in the logs... I am only forwarding port 8123 to 8123 at my remote location, but this should not be an issue?

**Comment by jlaitinen81** [comment]
I thought that this would somehow be related to the API, but I can manually create RESTful switches and they work just the way they should...

**Comment by postlund** [comment]
Can you try setting it up via YAML and just use the most basic config you possibly can (I.e. no filters, prefixes, etc)? I want to make sure it has nothing to do with config flow generating bad config entries.

**Comment by Merangle** [comment]
Hello 

I have exactly the same issue. 
Just installed the remote-assiatant component via hacs.
The only sensor I get is sensor.remote_connection_to_192_168_1_xx_8123 

i've also tried with this integration 

remote_homeassistant:
  instances:
  - host: 192.168.1.XX
    port: 8123
    secure: true
    verify_ssl: false
    access_token: !secret access_token_remote
    entity_prefix: "haremote_"
    include:
      domains:
      - sensor

And I don't get any remote entities 

I've also tried to set the sensors item in the hacs configuration with a tic on 'sensors' without success

and the log states
2021-03-27 11:53:33 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.remote_homeassistant
2021-03-27 11:53:33 INFO (MainThread) [custom_components.remote_homeassistant] Connecting to ws://192.168.1.16:8123/api/websocket
2021-03-27 11:53:33 INFO (MainThread) [custom_components.remote_homeassistant] Connected to home-assistant websocket at ws://192.168.1.16:8123/api/websocket

2021-03-27 11:53:37 INFO (MainThread) [custom_components.remote_homeassistant] Connecting to ws://192.168.1.16:8123/api/websocket
2021-03-27 11:53:37 INFO (MainThread) [custom_components.remote_homeassistant] Connected to home-assistant websocket at ws://192.168.1.16:8123/api/websocket

with a debug level set to error. 

However I get the information wit the restful api 
Any idea ?
Thanks for the component

**Comment by BlackMoon1190** [comment]
I have the same problem

**Comment by anhead** [comment]
I also have the same problem :/

**Comment by sshalyminov** [comment]
Same for me

**Comment by Klench** [comment]
I am experiencing the same issue, with a very simple configuration.

remote_homeassistant:
  instances:
    - host: !secret rpi_ha_ip
      port: 8123
      access_token: !secret rpi_ha_token
      entity_prefix: rpi_

**Comment by stats2909** [comment]
Hey all,  I had the same issues, 1 device and 1 entity, no matter what options I selected.

But look in your entities on your main system - you'll find them listed :)

**Comment by BCsabaEngine** [comment]
Same issue. Only the connection entity displays, other entities are visible on settigns panel. But not in system.
