### ISSUE TITLE
remote.send_command

### ISSUE THREAD

**Issue by michaelrch** [custom-components/remote_homeassistant#122]
I am trying to send commands via a remote control entity on a remote Hassio instance. It's an Apple_tv remote entity, loaded by the Apple TV integration on the remote hassio instance.
On the master hassio instance I can see the remote.apple_tv entity at the remote location via Remote_homassistant, but the remote.send_command service is not loading on the master hassio instance so I can't do anything with that remote.apple_tv instance.
Can this be fixed?

**Comment by postlund** [comment]
Yes, you need to make sure the `remote` component is loaded on the main instance. Please see:

https://github.com/custom-components/remote_homeassistant#missing-components
