### ISSUE TITLE
Configuration UI not showing input labels

### ISSUE THREAD

**Issue by Svanmark** [custom-components/remote_homeassistant#127]
The configuration UI is not showing labels on the input fields as shown in attached image.

Installed by cloning repo and copying custom_components/remote_homeassistant folder into my Home Assistant custom_components folder.

<img width="432" alt="Screenshot 2021-08-27 at 20 39 25" src="https://user-images.githubusercontent.com/457482/131174204-2603b8d3-316b-4eec-b0c5-7e0493b93fdb.png">

**Comment by postlund** [comment]
Are you sure you also copied the translations directory? That's the only reason I could see this happen.

**Comment by Svanmark** [comment]
Can now confirm that the translations file is there, still no text showing up.
