### ISSUE TITLE
Remote home assistant stopped working after update ha to 2021.10.0

### ISSUE THREAD

**Issue by maartenhendrix** [custom-components/remote_homeassistant#133]
After updating to 2021.10.0 i get this error and can’t see any of the remote home assistant sensors in the main home assistant.  
This error originated from a custom integration.

Logger: custom_components.remote_homeassistant
Source: custom_components/remote_homeassistant/__init__.py:403 
Integration: Remote Home-Assistant (documentation, issues) 
First occurred: 11:01:48 PM (83 occurrences) 
Last logged: 11:15:30 PM

instance id not matching: != 9844c3bee90d4c20ba50fb20c114717a

**Comment by patdemko** [comment]
> I have same issue after upgrade, but resolved by creating a new key on the remote system and readding the integration with that key

This didn't work for me.  I was able to delete and readd it with a new key, but it didn't pull in any of my entities for some reason. Are both of your systems on the 2021.10.0 or just the one with the remote home assistant integration?

**Comment by bartbakels** [comment]
Guys i took it back this morning, the remote entities where offline again and same error again

**Comment by pdecat** [comment]
As a quick work-around, I edited the `custom_components/remote_homeassistant/__init__.py` on my local installation of this component and inserted a `return True` statement before [line 400](https://github.com/custom-components/remote_homeassistant/blob/3.4/custom_components/remote_homeassistant/__init__.py#L400)

```
        def _async_instance_id_match(info):
            """Verify if remote instance id matches the expected id."""
            return True
            if not info:
                return False
            if info and info["uuid"] != self._entry.unique_id:
                _LOGGER.error(
                    "instance id not matching: %s != %s",
                    info["uuid"],
                    self._entry.unique_id,
                )
                return False
            return True
```

**Comment by henlagt** [comment]
I have more than one Remote HA instance and that's not working after the update to 2021.10.0. I tried both with configuration through yaml and the integrations page. I'm only able to get one instance is working. When I try to configure the second istance through integrations it says "Aborted. Already configured".

**Comment by draner686** [comment]
same here, get only one to work no multiple remote. Hope you get the time to Fix, on of the best integrations for me!

**Comment by gilperme** [comment]
This did it for me as well! Thank you @pdecat for sharing.

> As a quick work-around, I edited the `custom_components/remote_homeassistant/__init__.py` file on my local installation of this component on the master HA instance and inserted a `return True` statement before [line 400](https://github.com/custom-components/remote_homeassistant/blob/3.4/custom_components/remote_homeassistant/__init__.py#L400)
> 
> ```
>         def _async_instance_id_match(info):
>             """Verify if remote instance id matches the expected id."""
>             return True
>             if not info:
>                 return False
>             if info and info["uuid"] != self._entry.unique_id:
>                 _LOGGER.error(
>                     "instance id not matching: %s != %s",
>                     info["uuid"],
>                     self._entry.unique_id,
>                 )
>                 return False
>             return True
> ```
> 
> I then restarted my master HA instance.

**Comment by maartenhendrix** [comment]
Why not generate one and use a sensor  to read it from the remote instance?

**Comment by postlund** [comment]
I'm thinking more in the line of requiring this integration on both instances and just add a new view with the needed information instead.

**Comment by lpt2007** [comment]
I had same problem today when I update ha to latest version.

Is there an update to correct this?

**Comment by wantsoftat** [comment]
we are waiting for corrections))

**Comment by str2der** [comment]
Same here! Looking forward to an update! 😍

**Comment by BobbyMcGee22** [comment]
Me as well!  Please!  One of my favorite features!

**Comment by postlund** [comment]
Everyone will have the same error unfortunately, it's a breaking change. The solution I proposed above is what I would say the best one, it however requires the component being installed on the remote instance and it must somehow also be loaded (otherwise we can't register a new API view). This means adding `remote_homeassistant:` to the configuration. As a side-note, the location (name) is available via the `/api/config` endpoint.

**Comment by curt7000** [comment]
nice work @postlund , this which controls a remote custom thermostat I built, and your Apple TV integration are my two most relied upon integrations!  Hopefully they'll merge this soon.

**Comment by BobbyMcGee22** [comment]
YES!  I got it working again.  I think the solution to my problem was to manually update the files in /config/custom_components/remote_homeassistant (perhaps because original install was done using HACS?!?).  Even though I did tell it to Update Information, the content of the files weren't updated (It did report V.3.4).  Maybe I misunderstand the purpose of that command.  Then, i made a long-lived access_token on my master, put both the instances in the slave's /config/configuration.yaml and Voila!  The slave is back on the master in all it's glory!  Thanks a million @postlund

**Comment by sgurgul** [comment]
Does it mean that you guys (@BobbyMcGee22  and @lolouk44 ) were able to make it working back without updating the component with changes mentioned by @postlund  ??

**Comment by postlund** [comment]
Bah, that is because the remote endpoint has the actual `uuid` key but it is empty. That means new config entries are setup with an empty unique id (or possibly the empty string), which is not good. The instance id validation will also succeed as the id will be empty on both sides... I do not recommend setting up like that. @lukas-hetzenecker I think you should just merge and make a new release.

**Comment by henrikhjelm** [comment]
stange on 2021.10.0 to  2021.10.4 i can only be connect to one home assistant remote not 2 :-/

**Comment by postlund** [comment]
That is directly related to what I wrote in my previous post. After you have added one instance, all the following will collide with the first one so it doesn't work. You need the updates in my PR.

**Comment by hugalafutro** [comment]
Hi, 
I am using 2 remote HA instances and when this error first appeared I did nothing but changed the __init__.py as outlined in the workaround @ https://github.com/custom-components/remote_homeassistant/issues/133#issuecomment-938749909 on main HA instance and everything kept working.

With the release of 3.5 these are the exact and only steps I took:
1. installed remote_ha integration via hacs on both remote HAs
2. added 
```
remote_homeassistant:
  instances:
```
to both remote HAs configuration.yaml and restarted them from within HA ui.
3. deleted custom_components/remote_homeassistant/__init__.py which I previously modified on main HA  instance
4. updated remote_ha integration on main HA instance via hacs, and rebooted it.

... and every remote sensor still shows on main instance. I have not modified any config, nor did I create long-lived tokens and added them to the main instance as outlined in the readme. How is this possible, what am I doing wrong?

**Comment by postlund** [comment]
I don't understand what is not working? You say that "every remote sensor still shows on the main instance", isn't that what you want?

**Comment by hugalafutro** [comment]
@MEKadan  this is what I did on 1 master and 2 slaves after 3.5 :

Start from scratch. 
Uninstall remote_ha on both instances and delete all remote_homeassistant: from configuration.yaml if present.
Install remote_ha on master from hacs
Restart master ha from ui and do nothing else on it
Add
```
remote_homeassistant:
  instances:
```
to configuration.yaml on slave instance,
Install remote_ha on slave from hacs,
Restart slave ha from ui and wait till it comes back up,
Click on the Notification on slave it will pop-up saying it found new devices on network (master remote_ha) and select to Ignore it.
On master click on the same notification and configure the entities you want to pull from slave

_note: the last 2 steps I might've done in opposite order, bottom line is ignore the slave trying to pull from master and configure the integration only on master, selecting whichever entities you want it to pull off slave instance (s)._

**Comment by MEKadan** [comment]
Thanks for the clarification. However, most of the confusion comes a bit later.  

In both units when needed to fill in the "Configuration", is the "host" the one selected as a host from these two, or does this mean the current system hosting this copy of remote?

Then the acces token, e.g. in machine B, do I feed the long live token of machine B, or A? And same in machine A? B or A? Or does it depend which I wish to configure as a master?

**Comment by MEKadan** [comment]
OK, did not notice the last sentences, that is ignore configuring the remote, so I configure here as the host the machine I'm currently on? And the acces token is from which??

**Comment by hugalafutro** [comment]
correct, you only configure the integration on master. on slave you only modify the configuration.yaml. you create the long lived token on slave ha when you click on your ha user in the bottom left on menubar.

**Comment by MEKadan** [comment]
...and the remote_homeassistant folder & files are located in both machines under \config\custom_components

**Comment by MEKadan** [comment]
OK, seems to be working now, but when configuring from master machine, I used slave's address and token in the configuration screen. Master's did not work.

I can now see the entities and e.g. control lights from master, just like earlier after update.

However, just like earlier, when doing that I keep getting these into the log latest for example:

` Logger: homeassistant.helpers.service
Source: helpers/service.py:128
First occurred: 04:06:24 (8 occurrences)
Last logged: 04:24:25

    Unable to find referenced entities x, y, z`
