### ISSUE TITLE
Remote home assistant authorization error

### ISSUE THREAD

**Issue by richardcalgary** [custom-components/remote_homeassistant#147]
following upgrade on both master and slave to 3.5 I was getting an instance id does not match every 10 seconds, data was ok. I deleted the instance on the master and reloaded. I no longer get the instance id does not match, however I now get an invalidAuth every 10 seconds however data is still coming through as shown below.  I set up the remote instance using an ip address, port 8123, access token, and unchecked both of the SSL options.

2021-10-27 09:34:27 ERROR (MainThread) [custom_components.remote_homeassistant] failed to fetch instance info
Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 364, in _async_instance_get_info
    return await async_get_discovery_info(
  File "/config/custom_components/remote_homeassistant/rest_api.py", line 51, in async_get_discovery_info
    raise InvalidAuth()
custom_components.remote_homeassistant.rest_api.InvalidAuth
2021-10-27 09:34:37 ERROR (MainThread) [custom_components.remote_homeassistant] failed to fetch instance info
Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 364, in _async_instance_get_info
    return await async_get_discovery_info(
  File "/config/custom_components/remote_homeassistant/rest_api.py", line 51, in async_get_discovery_info
    raise InvalidAuth()
custom_components.remote_homeassistant.rest_api.InvalidAuth
2021-10-27 09:34:48 ERROR (MainThread) [custom_components.remote_homeassistant] failed to fetch instance info
Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 364, in _async_instance_get_info
    return await async_get_discovery_info(
  File "/config/custom_components/remote_homeassistant/rest_api.py", line 51, in async_get_discovery_info
    raise InvalidAuth()
custom_components.remote_homeassistant.rest_api.InvalidAuth

**Comment by ovizii** [comment]
> Huh, very strange, but I fixed the problem by doing this:
> 4. Removed long access token on remote HA instance and created a new one. Copied the token to the `configuration.yaml` on local HA instance.

How exactly did you copy the access token in configuration.zaml_

> 6. Installed Remote Home-Assistant on local HA instance and restarted HA (`remote_homeassistant` setup is in `configuration.yaml`)

Is this not supposed to be inside configuration.yaml on the remote instance and not the local one?

**Comment by uphillbattle** [comment]
> Is this not supposed to be inside configuration.yaml on the remote instance and not the local one?

As per the documentation (README.md), the remote instance only needs these two lines in `configuration.yaml`:

```
remote_homeassistant:
  instances:
```

The actual configuration of the link (between the two HA instances) is in `configuration.yaml` on the local instance.

**Comment by ivdimitro** [comment]
> Huh, very strange, but I fixed the problem by doing this:
> 
> 1. Removed Remote Home-Assistant integration on local HA instance
> 2. De-installed Remote Home-Assistant from remote HA instance AND local HA instance and restarted them both
> 3. Installed Remote Home-Assistant on remote HA instance
> 4. Removed long access token on remote HA instance and created a new one. Copied the token to the `configuration.yaml` on local HA instance.
> 5. Rebooted remote machine
> 6. Installed Remote Home-Assistant on local HA instance and restarted HA (`remote_homeassistant` setup is in `configuration.yaml`)
> 7. Voila! No error messages and the connection works. tada

I am not sure how you ended up with this voodoo magic but this is the only procedure that worked for connecting the server and the client. 
Thanks.

**Comment by jmsblah** [comment]
> Huh, very strange, but I fixed the problem by doing this:
> 
> 1. Removed Remote Home-Assistant integration on local HA instance
> 2. De-installed Remote Home-Assistant from remote HA instance AND local HA instance and restarted them both
> 3. Installed Remote Home-Assistant on remote HA instance
> 4. Removed long access token on remote HA instance and created a new one. Copied the token to the `configuration.yaml` on local HA instance.
> 5. Rebooted remote machine
> 6. Installed Remote Home-Assistant on local HA instance and restarted HA (`remote_homeassistant` setup is in `configuration.yaml`)
> 7. Voila! No error messages and the connection works. 🎉

What do you mean by "remove" in step one? is it the same as de-installed in step two?

**Comment by uphillbattle** [comment]
@jmsblah Remove/delete the integration - as opposed to the component, which is installed in HACS and de-installed in step 2. See arrow in picture below.
![image](https://github.com/custom-components/remote_homeassistant/assets/15340540/33fdbd00-b28e-4124-99c7-bc5b0f0e0823)
