### ISSUE TITLE
error after update to latest version

### ISSUE THREAD

**Issue by lpt2007** [custom-components/remote_homeassistant#148]
After update to 3.5 I have trouble to add connection.

Error:
You need to install Remote Home Assistant on this host and add remote_homeassistant: to its configuration.

![31 10 2021_15 01 27_REC](https://user-images.githubusercontent.com/38924279/139587438-97e054ea-da3c-4067-b17c-78c581062710.png)

**Comment by dimme** [comment]
I can confirm this error. It's a moment 22 situation.

**Comment by dimme** [comment]
On the remote instance you also need to add this to configuration.yaml:

```
remote_homeassistant:
  instances:
```

**Comment by lpt2007** [comment]
> remote_homeassistant:
>   instances:

Thx for replay

I added this to configuration.yaml but error still persist.

Any idea why? Before update all woked perfectly, without lines in configuration.yaml

**Comment by dimme** [comment]
You need to reboot the remote instance.

**Comment by r00tat** [comment]
I had the same issue. 

The docs now state: `This component must be installed on both the main and remote instance of Home Assistant`

This hasn't been the case and broke my connection. After installing it on both instances I had troubles on configuring it through the UI config flow, so I had to configure it through the yaml file.

**Comment by ovizii** [comment]
> I had the same issue.
> 
> The docs now state: `This component must be installed on both the main and remote instance of Home Assistant`
> 
> This hasn't been the case and broke my connection. After installing it on both instances I had troubles on configuring it through the UI config flow, so I had to configure it through the yaml file.

The docs seem to have changed, and I can no longer get this working, although it was working flawlessly. The docs currently say:

![image](https://user-images.githubusercontent.com/837902/172250532-8e4f7a04-50a5-43de-84af-f3677977344f.png)

Does anyone have “working and detailed" instructions to get a remote instance connected to the main instance?
