### ISSUE TITLE
Home.zone should be excluded it mess up the main HA home zone

### ISSUE THREAD

**Issue by TheGreatBorg** [custom-components/remote_homeassistant#151]
After each restart of the main HA the home zone for this devices get changed to the remote home.zone (if I check the map from the panel) if I check General setting the "home" is shown correct but I have to move the point a bit and press save. Then the Main HA "home" is correct again. 

Could the fixed Exclude domains be extended to include home.zone just like for the "persistent_notification" ?

I constantly get the "User input malformed" error so for now the Remote-HA Integration is not working. I might go back to yaml setup and skip the UI integration setup.

**Comment by CaptInsano** [comment]
I came here to request something similar.

Home.zone was messing up my setup so I excluded the Zone domain among others via UI integration and now am getting
 the "User input malformed" error.

![image](https://user-images.githubusercontent.com/332478/145881219-532a82f8-93ab-4ef8-9fa3-95c318ba2025.png)

Any advice on this error/fix?

**Comment by PhantoMMM** [comment]
Joining the question/
