### ISSUE TITLE
ConnectionStatusSensor implements device_state_attributes - HA 2021.12.3

### ISSUE THREAD

**Issue by ACrazyConcept** [custom-components/remote_homeassistant#157]
Getting this error with v3.5 in HA 2021.12.3

`Entity sensor.remote_connection_to_[redacted] (<class 'custom_components.remote_homeassistant.sensor.ConnectionStatusSensor'>) implements device_state_attributes. Please report it to the custom component author.`

Alse mentioned here https://github.com/custom-components/remote_homeassistant/issues/154#issuecomment-991913304. But it seems to be a separate issue and is not fixed by https://github.com/custom-components/remote_homeassistant/pull/155

**Comment by ACrazyConcept** [comment]
I think it is just to update the name:
https://community.home-assistant.io/t/2021-12-new-configuration-menu-the-button-entity-and-gorgeous-area-cards/365680/317

**Comment by lukas-hetzenecker** [comment]
Has already been fixed in aac178b737357492cf3beb60ec3494dcf0513c3a, will publish a new release now

**Comment by lukas-hetzenecker** [comment]
fixed in 3.6
