### ISSUE TITLE
Failed to connect to the server - url duck-dns

### ISSUE THREAD

**Issue by Pme1159** [custom-components/remote_homeassistant#160]
Hello,

I try to connect 2 HA instances by installing remote_homeassistant through HACS. 
The process worked for the remote instance but not at the level of the main instance.

I introduce hereunder the url of the remote instance and the long-life token created. The port is not 8123 but another dedicated port.
![image](https://user-images.githubusercontent.com/59808783/149821238-aa803158-1bf5-4745-8c8c-430b3a912b94.png)

I get the following response : 
![image](https://user-images.githubusercontent.com/59808783/149821423-a0e826c3-6256-4cbc-9f24-fe66e49329f6.png)

Thank you in advance.
Pascal

**Comment by Commandk35** [comment]
Do you have any solution for this I also face the same problem beacuse I use cloudflare Tunnel too

**Comment by zejdajan** [comment]
I am trying same thing with cloudflare tunnel, same problem.

**Comment by zejdajan** [comment]
I have already found a solution:
Create new user- for it then create new long term token.
In main HA in form use port: 443
