### ISSUE TITLE
Failed to connect to remote home assistant  - after upgrade to HA OS version 7.2

### ISSUE THREAD

**Issue by dinan5** [custom-components/remote_homeassistant#161]
After upgrading the remote instance to OS version 7.2, I can no longer connect to that instance. reverting the OS back to 7.1 removes the issues.

**Comment by mrzsilva** [comment]
Hi,
Follow the steps here,
https://github.com/custom-components/remote_homeassistant/issues/148

It worked for me also.

**Comment by dinan5** [comment]
Hi - thank you.  just to be clear, I've been running with the new Remote config requirements for many months.  this broke with the 7.2 os upgrade.  is that what you experienced?

**Comment by mrzsilva** [comment]
Correct
