### ISSUE TITLE
Error on clicking configuration under integrations

### ISSUE THREAD

**Issue by coolnetworks** [custom-components/remote_homeassistant#164]
Latest versions of core and OS, when installing the remote integration via HACS, it shows under hacs, but wont show in integrations so I can add it.

On a separate instance, same thing, it shows under integrations but shows "Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble" when clicking the configuration link under integrations.

"

## System Health

version | core-2022.2.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.98
arch | x86_64
timezone | Australia/Adelaide

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4640
Installed Version | 1.22.0
Stage | running
Available Repositories | 1051
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 255.3 GB
disk_used | 9.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.0.1), inception-mqtt addon (1.0), AppDaemon 4 (0.8.1), Studio Code Server (4.1.0), InfluxDB (4.3.0), Terminal & SSH (9.3.0), Let's Encrypt (4.12.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

**Comment by coolnetworks** [comment]
it will not open this page

https://user-images.githubusercontent.com/38924279/139587438-97e054ea-da3c-4067-b17c-78c581062710.png

**Comment by Vispen74** [comment]
I have the same problem on my remote instance, HA running in a docker container and the install made with HACS.

**Comment by Vispen74** [comment]
Tried to change so the docker install of HA was set to host, and the RPI HA set as reomote. No difernce, config not possible on any of the installations, so the issue are not related to hardware or setup.

**Comment by beccsjb** [comment]
I too am having the config flow: undefined error on both HASS servers, both running latest updates.

**Comment by Bisket25** [comment]
I'm trying to set it up for the first time, I'm having this issue as well

**Comment by coolnetworks** [comment]
I have figured it out. On the site that sends the data, it should not need configuring. On the site that receives the data, it will ask for details of remote site. All in the way you select the initial setup

**Comment by Bisket25** [comment]
Can you go into details about how you got it to work? I cannot get my remote instance to even get to the configuration stage.

**Comment by denperss11** [comment]
I get the same error.

**Comment by maphilli14** [comment]
I'm having similar errors and the guides/instructions do not work.  After adding via HACS, and selecting add integration on the master node, I see this which isn't in the docs / guides.

![image](https://user-images.githubusercontent.com/6034105/170520917-2c81062b-3201-4529-9583-a8da4d1305f0.png)

I did 'add remote' as I am on the main instance and the next screen is

![image](https://user-images.githubusercontent.com/6034105/170521189-61486314-9aac-43eb-bc98-547e119d8a0d.png)

adding the remote errors off with (false token for sharing)

![image](https://user-images.githubusercontent.com/6034105/170521350-5a34cb0c-7888-40a6-bd7b-c8af3de10c56.png)


Trying to setup remote 1st isn't working either and I'm confused!

**Comment by coolnetworks** [comment]
There is not config on the remote host.

You just need a logon created.

All config happens on the main host.

**Comment by lukas-hetzenecker** [comment]
fixed with the latest release
