### ISSUE TITLE
how connect to remote instante to nabucasa https? 

### ISSUE THREAD

**Issue by satedone** [custom-components/remote_homeassistant#169]
![изображение](https://user-images.githubusercontent.com/60436161/163218119-0db7c86b-ea5a-44ef-a391-2be84516756d.png)

There are no problems with connecting with a fixed ip.

But I can't connect to the address from the nabucasa server.

What is the problem?

**Comment by uSlackr** [comment]
try removing https and instead click the "secure" box

**Comment by satedone** [comment]
Thank you. But it doesn't work. All similar options with http, port, secure and so on, I have already tried. Does not work.

Interesting, anyone has any experience with this integration and nabucasa link?

**Comment by chris8837** [comment]
I just added Nabu Casa on a second node or separate house.  I can confirm it working. I can’t remember the exact format but you def dont need the ‘https://‘ and I think after ‘.ui.nabu.casa’ either

I would play around with removing areas of the nabu casa link until you find the right one. Wish it was on the instructions but it works for sure.

**Comment by McPostal** [comment]
Did you ever figure this out? I'm having the same problem.

**Comment by chris8837** [comment]
Yeah. My prior post above. 

Don’t need the ‘https://‘ and I think after ‘.ui.nabu.casa’ either. No port necessary.

**Comment by satedone** [comment]
Yes, thank you. I checked with myself. That's exactly how it works. 

youradress.ui.nabu.casa (without https://)
yourtokken (I have 183 characters)
port 443

**Comment by satedone** [comment]
And for the server with white ip I remove the security check and certificate

youripadress (without https:// and http)
yourtokken (I have 183 characters)
port (any one which is open to external access to HA)
