### ISSUE TITLE
'Already configured' prevents adding a remote node

### ISSUE THREAD

**Issue by AndrewGWalsh** [custom-components/remote_homeassistant#175]
I have a main HA which runs in a server room and 3 small HAs which run on Debian on Pis around the house.

One connects ok, the other two get an 'Already configured' message.  I have hunted around the forum and the issues on this repository but can't see anything.

I did have all 3 set up at a point in the past via yaml but as the Zeitgeist is to eschew this in favour of configflow....

I wonder if some setting configuration file needs wiping out somewhere?

I am on latest everything.

**Comment by bfeignerkmc** [comment]
I'm seeing the same thing when I try to add a 2nd remote HA instance

**Comment by uSlackr** [comment]
Have you tried using YAML to config vs the UI?

**Comment by AndrewGWalsh** [comment]
I have tried with YAML too, that also did not work. The error message suggests that a configuration might need wiping - I don't suppose you know where it lives?

**Comment by uSlackr** [comment]
Deleting the component I assume

\\Greg

**Comment by AndrewGWalsh** [comment]
I tried that a couple of times but no luck. :-(

**Comment by jmrassuncao** [comment]
Any news on this? I'm also getting the error ("Already configured") when trying to add a second remote node from the UI. If i try the YAML config, only the first node connects...

Everything is updated (HA, Core, HACS, Remote HA...).

**Comment by mlavelle42** [comment]
Same problem for me. I can add a total of 2 remotes but the third causes a response "Already Configured" - I know it isn't.

**Comment by jmrassuncao** [comment]
Well, i think i've came up with something...

I've searched for the file where the configurations was and found it. It's stored in `/config/.storage/core.config_entries`, in there searched for the entry `remote_homeassistant`. Copied the complete configuration and replaced the necessary entries (entry_id, title, host, access_token, service_prefix, unique_id, etc.) and rebooted.

When the system went up again, a second Remote Home-Assistant entry was there with all the remote entities!

The only thing i don't understant is an error on the logs saying:

`Platform remote_homeassistant does not generate unique IDs. ID bb3d3aa51ded43518501c6c6b88fe27f already exists - ignoring sensor.remote_connection_to_sigrev001`

**Comment by mlavelle42** [comment]
Interesting. I checked core.config_entries and only found the 2nd or last remote I configured. Both remotes show up in the Integrations block but only the 2nd entry can be accessed for configuration. The core.device* and core.entity* files are really big - as expected. For the one remote I have working this is _very_ impressive software. Hope it will be possible to have more than 1 remote soon.

**Comment by lukas-hetzenecker** [comment]
Did you by any chance copy the configuration folder between all instances? In that case, they all have the same UUID, and remote_homeassistant cannot differentiate between them. 

Can you check the file `.storage/core.uuid` in the configuration folder of each instance, and see if they have different uuid values?

Please re-open this issue if you still encounter the problem with different UUIDs.

**Comment by AndrewGWalsh** [comment]
You are quite right - I duplicated setup and they had the same core.uuid, now fixed (I deleted the file and it created a new one with a different uuid).  Thank you.

Kind thoughts,

Andrew
