### ISSUE TITLE
heartbeat failed & Detected integration that uses deprecated `async_get_registry`

### ISSUE THREAD

**Issue by comet424** [custom-components/remote_homeassistant#180]
dont know what these errors are but keeps coming up 

Logger: custom_components.remote_homeassistant
Source: custom_components/remote_homeassistant/__init__.py:460
Integration: Remote Home-Assistant ([documentation](https://github.com/custom-components/remote_homeassistant), [issues](https://github.com/custom-components/remote_homeassistant/issues))
First occurred: 8:49:30 AM (2 occurrences)
Last logged: 8:57:19 AM

heartbeat failed

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 8:46:45 AM (1 occurrences)
Last logged: 8:46:45 AM

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for remote_homeassistant using this method at custom_components/remote_homeassistant/__init__.py, line 430: device_registry = await dr.async_get_registry(self._hass)

**Comment by lukas-hetzenecker** [comment]
This is fixed now
