### ISSUE TITLE
Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead.

### ISSUE THREAD

**Issue by rchamp26** [custom-components/remote_homeassistant#181]
the latest version of home assistant (2022.7.1) shows a deprecated method within the current version of remote-homeassistant

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for remote_homeassistant using this method at custom_components/remote_homeassistant/__init__.py, line 430: device_registry = await dr.async_get_registry(self._hass)

**Comment by Jens-Wymeersch** [comment]
@postlund Pierre, I have the same issue as @rchamp26 making the component irrelevant as I can't see any entities of the host. Can you please have a look what can be done ?

**Comment by rchamp26** [comment]
The integration still works for me, but I assume, this will break soon in a future update. These warnings from HA are appreciated to bring awareness of a deprecated method prior to just breaking. I'm not a coder so not sure what to change. I messed with just changing that line, but it broke the integration so I rolled back to the current version, where it works, but get the deprecated warning

**Comment by roberttco** [comment]
Is this fixed in pr #183 and pr #176 ?

**Comment by lukas-hetzenecker** [comment]
Yes, this is fixed now
