### ISSUE TITLE
Cannot update settings with blank Entity Prefix

### ISSUE THREAD

**Issue by Larry-Home** [custom-components/remote_homeassistant#185]
After setting up the integration, if you then go in and try to make changes leaving the Entity Prefix field empty (as suggested in installation process and desired) it will produce the following error:

![Screen Shot 2022-07-30 at 10 41 13 AM](https://user-images.githubusercontent.com/26754378/181924640-de5588bb-e38d-4db4-975c-2256cb845ef8.png)

**Comment by sunfos2019** [comment]
Confirm the same.
v 3.7

**Comment by lukas-hetzenecker** [comment]
Cannot reproduce, setting the "Entity prefix" to a blank value works for me (regardless to what it was set previously)
Home Assistant 2022.10.4, remote_homeassistant 3.7
