### ISSUE TITLE
`websocket connection had an error` due to `MESSAGE_TOO_BIG`

### ISSUE THREAD

**Issue by Zen3515** [custom-components/remote_homeassistant#226]
When message size exceed the default of 4MB, the integration breaks.

Example log:

```
INFO (MainThread) [custom_components.remote_homeassistant] Connected to home-assistant websocket at wss://ha.example.com:443/api/websocket
ERROR (MainThread) [custom_components.remote_homeassistant] websocket connection had an error
```

When logging the message it become something along this line

```
WSMessage(type=<WSMsgType.ERROR: 258>, data=WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 4449457 exceeds limit 4194304'), extra=None)
```

I think the solution is to let user increase the size limit of message from 4194304 (4 * 1024 * 1024)

**Comment by zenoxygenai** [comment]
@lukas-hetzenecker Is is possible to have this merge?

I really do need this feature.

**Comment by Zen3515** [comment]
@lukas-hetzenecker is it possible to have this merged?

I really do need this feature.
