### ISSUE TITLE
Homessistant web interface stuck with this error in console Uncaught (in promise) {code: 'unknown_error', message: 'Unknown error'}

### ISSUE THREAD

**Issue by magnum** [custom-components/remote_homeassistant#235]
see https://github.com/home-assistant/frontend/issues/16920#issuecomment-1605829803 

starting some weeks ago my homeassistant (supervised, on a raspberry pi4) stopped randomly responding via web interface; this is the error i can see in web inspector:
```
Uncaught (in promise) {code: 'unknown_error', message: 'Unknown error'}
```

in the resources panel of the browser inspector i can i see it fails to get resources such as
```
https://[my-personal-id].ui.nabu.casa/frontend_latest/no-source/node_modules/home-assistant-js-websocket/dist/collection.js (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)
```
and a lot more others similar;

it happens most of the times after an upgrade of homeassistant core; sometimes if i try and try to reboot it works, it goes of for some hours, and then boom! when i try to use the web interface is doesn’t load returning me the error cited above (“Uncaught (in promise) etc.”)

### Describe the behavior you expected

i expected the dashboard to load

### Steps to reproduce the issue

1. reboot homeassistant instance
2. open the dasboard

### What version of Home Assistant Core has the issue?

2023.6

### Javascript errors shown in your browser console/inspector

```txt
dashboard:1 Uncaught (in promise) {code: 'unknown_error', message: 'Unknown error'}
```

**Comment by ACiDGRiM** [comment]
Is this #234 ?

**Comment by magnum** [comment]
it seems related...

**Comment by magnum** [comment]
still get the error, and homeassistant frontend do not show up... 
<img width="1990" alt="Screenshot 2023-08-25 alle 14 07 37" src="https://github.com/custom-components/remote_homeassistant/assets/9384/6e153d94-41ed-49ae-9b39-41b4c770ced7">
