### ISSUE TITLE
Ignoring invalid device info: Invalid device info {'configuration_url': 'https://192.168.1.12:8123', 'name': 'Home Assistant'}

### ISSUE THREAD

**Issue by comet424** [custom-components/remote_homeassistant#248]
i get this error now after updating to 2023.8.1  not sure how to fix it?  i dont see option to enter a name?

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:624
Integration: Sensor (documentation, issues)
First occurred: 1:23:32 PM (2 occurrences)
Last logged: 1:23:32 PM

Ignoring invalid device info: Invalid device info {'configuration_url': 'https://192.168.0.10:8123', 'name': 'Home Assistant'} for 'remote_homeassistant' config entry: device info must include at least one of identifiers or connections
Ignoring invalid device info: Invalid device info {'configuration_url': 'https://192.168.1.12:8123', 'name': 'Home Assistant'} for 'remote_homeassistant' config entry: device info must include at least one of identifiers or connections

**Comment by MattWestb** [comment]
I is getting the same error on HA 2023.8.0 and is having one production system as master and 3 test system sending all sensors to the master and all looks working OK like button press on IKEA Rodret Dimmer is being OK reported over Zigbee at the same time EVE Energy is reporting all power over thread in the same Billy module.

**Comment by fth-mt** [comment]
Getting same errors, rolling back to 7.3 fixed it. Am on the latest Remote_homeassistant.

**Comment by domgregori** [comment]
Same error on HA 2023.8.1

**Comment by lukas-hetzenecker** [comment]
Thanks for reporting, should be fixed in the latest release

**Comment by dinan5** [comment]
Great work, thank you!
