### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by waato65** [custom-components/remote_homeassistant#262]
Hello great community!

I can't get this to work after i made a fresh installation of HA. It was working before. The main instance is at home and the remote instance is at our holiday-house. 

What do i put in the field "Host" on my home instance when configuring the integration? I have tried the name of the remote HA instance, the remote local IP adress of HA ++. Nothing works. I only get the message: Failed to connect to server.

I have been following the instructions from here: https://github.com/custom-components/remote_homeassistant

Today i got help from a friend who is an experienced HA user, but he too failed trying to fix this.

Another user have had the same problem and gave up, see: https://community.home-assistant.io/t/remote-home-assistant-wont-connect-to/461183

I have tried everything that he tried.

Can anyone help?

Regards Johnny
---

Solved! Found at last this great video on Youtube: https://www.youtube.com/watch?v=aiyK8LytKYQ

**Comment by paltheimer** [comment]
I am still facing the same issue. Both HA instances are reaching each other by using IP and / or hostname. The network connection via VPN is open for all the ports, I can access via browser, telnet and ssh/scp. I tried with/without secure, creating new long-live token, another user ... everything. Just getting "Failed to connect to server." I can't find any more information about that in logfiles, etc. Does anyone know, how to debug this behaviour?
