### ISSUE TITLE
2023.11.2 update broke automations

### ISSUE THREAD

**Issue by billkater** [custom-components/remote_homeassistant#263]
I just updated to HA 2023.11.2. Now none of my Z-Wave device are showing up in my main instance of HA.  And any automation that used a Z-Wave device from the remote instance wont work anymore. Z-Wave devices are not being pulled from the remote to the main HA instance. I can see the entities though.

Here is a automation:

alias: Bar Open Turns ON Bar Closed Turns OFF
description: Bar open turns on when switch on comes on. Bar closed turns off.
trigger:
  - platform: device
    type: turned_on
    device_id: fb81b2bd1a57809cae5a0ca562872522
    entity_id: switch.shed_switch_1
    domain: switch
condition: []
action:
  - type: turn_on
    device_id: a46992e318a4110954b730c8053c0c8b
    entity_id: light.bar_open
    domain: light
    brightness_pct: 100
  - type: turn_off
    device_id: c8fdad698545dba287be6595d57c77f5
    entity_id: light.bar_closed
    domain: light
  - type: turn_on
    device_id: c97aede2eb7074ff77d04b8583539d1e
    entity_id: light.pabst_light
    domain: light
mode: single

Here is the error in the logs:

Logger: homeassistant.components.automation
Source: components/automation/config.py:108
Integration: Automation (documentation, issues)
First occurred: 2:48:05 AM (2 occurrences)
Last logged: 2:48:05 AM

Automation with alias 'Bar Open Turns ON Bar Closed Turns OFF' failed to setup triggers and has been disabled: Unknown device 'fb81b2bd1a57809cae5a0ca562872522'

![error](https://github.com/custom-components/remote_homeassistant/assets/98135456/3df65aab-9744-432a-8602-bbbb81e7b8c1)

![error 2](https://github.com/custom-components/remote_homeassistant/assets/98135456/ffe3dcd1-0641-41d1-b0de-e582a6c027f9)

**Comment by billkater** [comment]
I restored a backup from 2023.10.5 and all my automations worked. But the devices of the remote HA still don't show in the main instance, just the entities. So it must have been this way for awhile. I just dont understand why my automations were working. I tried to create a automation exactly like the one listed and couldn't. with the visual editor. But I could do it in Yaml.

So I would say this isnt a problem with the remote_homeassistant integration.

**Comment by ACiDGRiM** [comment]
> I restored a backup from 2023.10.5 and all my automations worked. But the devices of the remote HA still don't show in the main instance, just the entities. So it must have been this way for awhile. I just dont understand why my automations were working. I tried to create a automation exactly like the one listed and couldn't. with the visual editor. But I could do it in Yaml.
> 
> So I would say this isnt a problem with the remote_homeassistant integration. 

Sometimes reloading the integration helps

I do suggest adding a prefix to entities even if it's not optional
