### ISSUE TITLE
Configuration stuck with button.press in remote services

### ISSUE THREAD

**Issue by ezeghers** [custom-components/remote_homeassistant#268]
I have remote home assistant working but I wanted to make a change to the configuration. When I go in there however, I can't change anything because of a user input malformed error. It is pointing to the button.press selection in the Remote Services section (see screen image). I assume that got in there from the initial set up but now I have no way to remove it either. There also appears to be other "cover" items in there that would cause the same issue. Any help would be appreciated.

![Screenshot 2024-01-15 8 21 51 PM](https://github.com/custom-components/remote_homeassistant/assets/17528238/68f30d27-2c98-4eff-8281-4edd9acf5fa2)

**Comment by MattWestb** [comment]
I think deleting the integration and hope its deleting the settings and waiting one minute / restart HA and adding it new is the easiest way trying getting it working OK if not patching the data in the storage folder of HA.

**Comment by ezeghers** [comment]
Yes, had to delete and re-add the integration.
