### ISSUE TITLE
Still in development? Or is this dead?

### ISSUE THREAD

**Issue by michael-hermsen** [custom-components/remote_homeassistant#276]
Last commit 7 months ago, and a lot has changed on the home assistant side.

Is this integration stil a thing, 

I want to use it but dont want the Risk that its gona break something with al those new part being added with every home assistant update, and this components last update was a long time ago.

Or maby security issues..

**Comment by gsaurer** [comment]
I am using it for different locations and it works great, but the lack of responses is not encouraging at the moment. There are several pull requests sitting for month now.
