### ISSUE TITLE
Cloudflare access

### ISSUE THREAD

**Issue by SamSenassi** [custom-components/remote_homeassistant#280]
Hello, I use two home assistant instances. One at home and one in my campervan. When using nabu casa I was able to use the remote homeassistant to expose the campervan entities to my home instance. However, since transferring to cloudflare I am no longer able to connect. Does anyone have any ideas as to how I can get it working again?! I have deleted the remote assistant entry in the integration but when inputting my cloudflare details in it returns with "failed to connect to server"

Thank you in advance

**Comment by niklasnoren** [comment]
Seem to have similar issue, described here: 

https://community.home-assistant.io/t/cant-get-remote-homeassistant-to-work-what-might-be-wrong-or-what-is-a-better-setup/717818

**Comment by FireFingers21** [comment]
Are you using the correct port? A lot of people assume the default 8123 port gets used for everything, but if you're accessing HA through HTTPS using a Cloudflare Tunnel, you need to connect with port 443.

**Comment by niklasnoren** [comment]
> Are you using the correct port? A lot of people assume the default 8123 port gets used for everything, but if you're accessing HA through HTTPS using a Cloudflare Tunnel, you need to connect with port 443.

You're right. Changed to 443 and it worked fine.
