### ISSUE TITLE
Randomly stopped working and now not installing

### ISSUE THREAD

**Issue by Flodapo** [custom-components/remote_homeassistant#325]
I have 2 instances Linked together and the host one randomly stopped working. In my messenges it said that it was missconfigured but I didn't touch anything, not even an update. I reinstalled it but now I can't add it in my integrations (in hacs it downloads and installs but I can't add it in the integration section of ha). When trying to add the integration I get: Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}. The Remote instance has no issues, it just can't connect.

**Comment by Flodapo** [comment]
Here are the logs
![Screenshot_20241107_104916_Chrome](https://github.com/user-attachments/assets/177a2d2f-c10a-44d1-975c-099c2c356ace)

**Comment by r0bb10** [comment]
here the manual fix that works https://github.com/custom-components/remote_homeassistant/issues/321#issuecomment-2461009442

**Comment by Flodapo** [comment]
Why is That necessary?

**Comment by kalwadi** [comment]
you have updated to latest version of HA and this component is not currently compatible because of changes made in that version. Until this component is updated by the developer you can manually fix it for yourself by applying the fix.

**Comment by lukas-hetzenecker** [comment]
Fixed with #323
