### ISSUE TITLE
Getting "Invalid config" on startup

### ISSUE THREAD

**Issue by DST73** [custom-components/remote_homeassistant#327]
If HA starts I get "Invalid config" in the notifications and I can't access the HA remote devices anymore

I am on HA 2014.11.0

![grafik](https://github.com/user-attachments/assets/1946aa24-60f5-4cb6-91e2-6c4a5c3c2435)

The following error shows up

![grafik](https://github.com/user-attachments/assets/f347dd9c-6d7f-49da-8b80-f9635e4dd38a)

**Comment by jasonmotylinski** [comment]
Looks like a commit was made 2 hours ago to address this error:
https://github.com/custom-components/remote_homeassistant/commit/576363b864c926f18be700cc8fbc4891e509f1ed

**Comment by tdoclot** [comment]
Same issue after upgrading from 2024.10.4 to 2024.11.0

**Comment by JanS328** [comment]
Same issue after upgrading from 2024.10.4 to 2024.11.0

**Comment by jasonmotylinski** [comment]
Did you upgrade to remote_homeassistant 4.30 in HACS? Upgrading to 4.3 solved the issue on my install (running HA 2924.11)

**Comment by tdoclot** [comment]
Yes, Remote homesaddistant 4.3 solved the issue

Le jeu. 7 nov. 2024 à 19:54, Jason Motylinski ***@***.***> a
écrit :

**Comment by DST73** [comment]
Remote homesaddistant 4.3 solved the issue for me too
