### ISSUE TITLE
Detected that custom integration 'remote_homeassistant' sets option flow config_entry explicitly

### ISSUE THREAD

**Issue by SupremeSports** [custom-components/remote_homeassistant#331]
Started having this issue with v4.4 since HA version 2024.12

`Detected that custom integration 'remote_homeassistant' sets option flow config_entry explicitly, which is deprecated at custom_components/remote_homeassistant/config_flow.py, line 208: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/custom-components/remote_homeassistant/issues`

**Comment by Ferdinand99** [comment]
I get the same error and it won't give any values to the main home assistant system. This happened after updating to 2024.12.0 and are still a issue on Core "2024.12.1" / Supervisor "2024.11.4"

**Comment by SupremeSports** [comment]
Fixed by [version 4.5](https://github.com/custom-components/remote_homeassistant/releases/tag/4.5)

**Comment by SupremeSports** [comment]
Fixed by [version 4.5](https://github.com/custom-components/remote_homeassistant/releases/tag/4.5)
