### ISSUE TITLE
Warning messages in logs: Unable to find referenced entities

### ISSUE THREAD

**Issue by jacekpaszkowski** [custom-components/remote_homeassistant#39]
Since version 0.106.x i get warinings in HA logs like:

```
2020-03-09 00:15:46 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.slave2_shenzhen_neo_electronics_co_ltd_wall_switch_1_channel_switch_5
```

**Comment by kahnman** [comment]
I am also getting these warnings. I get them on my master instance running 0.109.2. Is this something I need to worry about?

**Comment by lukas-hetzenecker** [comment]
Not sure, probably not. I think home-assistant just keeps tracks of all entities now - and might not know from where the remote entities are coming from. If everything is still working, I wouldn't worry about it.

**Comment by postlund** [comment]
For some reason I see this in my production instance, but I cannot reproduce it in my development instance. It's a bit annoying as debugging is much harder when running on HassOS.
