### ISSUE TITLE
Accessing zwave.set_config_parameter from master instance

### ISSUE THREAD

**Issue by kahnman** [custom-components/remote_homeassistant#45]
I have a master instance which is where I have almost everything (automations, scripts, scenes, etc.). My secondary instance is where a zwave radio is being used to connect zwave devices. One such device is an Inovelli Dimmer Switch, which has a LED on it that can be used for custom notifications. 

To make use of this LED, I need to call the `zwave.set_config_parameter` service. I have done this successfully from my secondary instance (where zwave is configured), but (not surprisingly) my master instance doesn't know what the `zwave.set_config_parameter` service is. 

I tried adding `zwave.set_config_parameter` to the list of `subscribe_events:` in my master instance config, but that didn't seem to work.

Is there any way to expose the `zwave.set_config_parameter` service to the master instance? 

Thanks!

**Comment by kahnman** [comment]
Hi @lukas-hetzenecker, 

Any thoughts on this? Is this possible or should I try and figure out a work around?

Thanks for your time!

Cheers.

**Comment by motherchaser** [comment]
I'm interested in doing this as well. With some of the recent updates to HA .111 and the effort on z-wave has sped up reboot times drastically. I wiped my Z-Wave network several times over the last week with the Aeotec Gen5 and Nortek HUSBZB-1. I noticed a considerable improvement in Z-Wave network boot times by adding my Inovelli Dimmers as "unsecured". I have Schlage Touchpad Deadbolts and those have to be added as Secured. 

Side Note - At one point I was trying to pull those locks into HA from SmartThings and just recently switched them all back.

**Comment by ccsliinc** [comment]
@lukas-hetzenecker I am trying to run lock.set_usercode from my master instance.  The first hurdle which I think may have been overkill was the need to add a usb zwave stick into the master machine and enable zwave.  This allowed the master instance to have the services available.  When I call the service on the master I am receiving the following error:

`2020-07-10 15:06:48 ERROR (MainThread) [homeassistant.components.automation] FrontNorthDoor Add Code: Error executing script. Unexpected error for call_service at pos 1: 15
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 153, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 656, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1299, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/zwave/lock.py", line 175, in set_usercode
    lock_node = network.nodes[node_id]
KeyError: 15`

My 2 questions are.

1. I tried to load the zwave domain only using zwave: in the bottom of the configuration.yaml.  It will not fully load the domain without a USB dongle in the master setup which I do not need.  Is there another way to fully load the domain.
2. How do I call these remote services from the master without running into the error pasted above.

Thank you for any help you can offer.

**Comment by jhein05** [comment]
I would love this too.

**Comment by postlund** [comment]
I believe this to be another case where the component takes control of the hardware rather than representing it via entities. This component cannot handle those cases. But I have added a workaround for it called "proxy services". It allows you to set up new services that proxies calls to another instance, e.g. a service called `zwave.summer_house_set_config_parameter` could be set up which would be forwarded to the `zwave.set_config_parameter` service on the other instance. It's more or less what you do, @jhein05, but more transparent. Errors are also propagated back to the master instance.

It's currently a PR, see #90, but it would be great if you could try it out and let me know if it works. Have a look at the changes to README.md for more details.

**Comment by postlund** [comment]
I merged #90 earlier today, so it is ok to run from master now.

**Comment by postlund** [comment]
If you experience any problems, please open the issue again as I consider it to be done now.
