### ISSUE TITLE
Mediaplayer component (custom:mini-media-player and media-control) not showing artwork in Lovelace

### ISSUE THREAD

**Issue by mindtripper** [custom-components/remote_homeassistant#48]
Hi!

This is a great component! Home Assistant Remote simplifies my setup immensely. Tip of the hat to the devs! 

I have a question relating to media_player component.
Album artwork will not show in lovelace, but controlling media works just fine.

Primary and Secondary instance of the media_player show the same attributes and values:
Primary (media_player.vardagsrum_2)
volume_level: 0.21229049563407898
is_volume_muted: false
media_content_id: spotify:track:27Xlqkl3rtEzAOaN4VM7zd
media_content_type: music
media_duration: 202.306
media_position: 0.67
media_position_updated_at: 2020-07-23T06:54:11.329444+00:00
media_title: I Really Want It
media_artist: A Great Big World
media_album_name: Is There Anybody Out There?
app_id: CC32E753
app_name: Spotify
entity_picture_local: /api/media_player_proxy/media_player.vardagsrum_2?token=<SAME BUT REMOVED>
friendly_name: Vardagsrum
entity_picture: https://i.scdn.co/image/ab67616d00001e02554488d0c51967b1654d8ce5
supported_features: 21439

Secondary (media_player.vardagsrum_2)
volume_level: 0.21229049563407898
is_volume_muted: false
media_content_id: spotify:track:27Xlqkl3rtEzAOaN4VM7zd
media_content_type: music
media_duration: 202.306
media_position: 0.67
media_position_updated_at: 2020-07-23T06:54:11.329444+00:00
media_title: I Really Want It
media_artist: A Great Big World
media_album_name: Is There Anybody Out There?
app_id: CC32E753
app_name: Spotify
entity_picture_local: /api/media_player_proxy/media_player.vardagsrum_2?token=<SAME BUT REMOVED>
friendly_name: Vardagsrum
entity_picture: https://i.scdn.co/image/ab67616d00001e02554488d0c51967b1654d8ce5
supported_features: 21439

Artwork shows just fine on Primary, but not on Secondary. It's just blank/orange. but interestingly album art shows up in "more-info" . Anyone had similar issues or ideas as to how to make artwork display properly?

![media](https://user-images.githubusercontent.com/26619531/88260237-41557f80-ccc4-11ea-9d7e-6618f452be8e.jpg)

Thanks in advance

**Comment by lukas-hetzenecker** [comment]
Same issue as with #29
