### ISSUE TITLE
Devices not showing up in main HA instance that is connecting to the remote instance

### ISSUE THREAD

**Issue by mg0716** [custom-components/remote_homeassistant#69]
I was able to get a successful bridge between a normal and remote HA instance and so I thought all was going well. But when I tried to start up an automation, I noticed that one of the "remote" devices was not available—leading me to realize that HA Remote didn't donate **any** devices at all. While I very well could be missing something obvious here, I couldn't find anything in the documentation to lead me in the right direction unfortunately and am left very confused.

Is this something that HA Remote currently supports?

**Comment by postlund** [comment]
Just to verify: you want to be able to use device triggers and such, right?

**Comment by thoppa** [comment]
I’m not sure what OP was asking, but I would like to use device triggers.

**Comment by TMidi84** [comment]
Has anyone been able to sort this out. I setup my system this week and I too  am not seeing any devices on my main instances.

**Comment by postlund** [comment]
Devices and all those new features are not supported, that's why basically.

**Comment by TMidi84** [comment]
I am confused. So using the main instance I won't see any devices added from my remote instances.  What new features are you referencing? Can you please elaborate?

**Comment by postlund** [comment]
What is supported currently are entities (with state updates of course) and services. Things such as devices (triggers, conditions), entity register (to change entity id for instance) and areas are not propagated back to the main instance. As these things are persistent in a local database,  it's *really* hard to implement these features as we would need to duplicate what's in the databases of the remote instance in the main instance. We would also have to clean up if we lose connection an keep track of state changes properly.  Nothing is impossible, it's just extremely hard to implement without having support in core for such a things.

**Comment by TMidi84** [comment]
Thank you so much for that clarification. So I should be seeing at least the entities  showing up in my main HA instance?

**Comment by postlund** [comment]
@controlcde I answered in your other issue.

**Comment by ACrazyConcept** [comment]
> 
> 
> extremely hard to implement without having support in core for such a things.

Any idea what such a support in core would look like?
