### ISSUE TITLE
Way to make entities persist?

### ISSUE THREAD

**Issue by ACrazyConcept** [custom-components/remote_homeassistant#70]
Wondering if there is a way to make discovered entities persist. I have some sensors that only update once or twice per day and they seem to cause trouble if I want to use the states for other template sensors etc.

**Comment by postlund** [comment]
I think it might be possible to accomplish this to some extent by supporting the entity registry. When I get some time to experiment, I will prototype support for that. It will only work for entities with a `unique_id`.

**Comment by LazyTarget** [comment]
Hi
I am one that would be very interested in this feature :P
This has the potential to help for various scenarios
