### ISSUE TITLE
Remote lock not working

### ISSUE THREAD

**Issue by Vartkat** [custom-components/remote_homeassistant#86]
running home-assistant-remote latest.
Both instances on the same LAN subnet

Slave has zwave locks paired using Open ZWave beta (but the behaviour was the same with the traidtionnal ZWave integration)

config is : 
```
remote_homeassistant:
  instances:
  - host: 192.168.1.249
    port: 8123
    access_token: !secret access_token
    entity_prefix: cabs_
    subscribe_events:
      state_changed
        - service_registered
        - zwave.network_ready
        - zwave.node_event
    include:
      domains:
      - sensor
      - switch
      - zwave
      - lock
      - climate
      entities:
      - binary_sensor.rpi_power_status
```
When a ZWave lock  is asked to lock or unlock Home Assistant fires a message saying Call to lock/unlock service failed.

I've tried a workaround by putting the slave machine interface in panel : 
panel_iframe:
```
  cabins:
    title: 'Cabins'
    url: 'https://externalURL.duckdns.org/lovelace/default_view'
    icon: mdi:home-group
```
but I'm facing a authentification problem as when the slave interface comes in the screen it asks for a login. I would like it to not ask and use the authentication token (or any other means) so that the end user of the interface doesn't have to login twice (hard to explain why there's two logins). 
If there's a way to do that or to make the lock.unlock service work I'll be happy to know how to do it.

Nothing noticable in HA logs nor in Supervisor.

**Comment by postlund** [comment]
Don't see any reason why it shouldn't work. There should be something in the log file?

**Comment by Vartkat** [comment]
Here is the HA log,
```
2020-12-14 16:37:20 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for lyric which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-12-14 16:37:20 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for remote_homeassistant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-12-14 16:37:20 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-12-14 16:37:20 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-12-14 16:37:21 WARNING (MainThread) [homeassistant.components.recorder] The 'purge_interval' option is deprecated, please remove it from your configuration
2020-12-14 17:58:55 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from ubnt (192.168.1.1) (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:78.0) Gecko/20100101 Firefox/78.0)
2020-12-14 17:59:07 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from ubnt (192.168.1.1) (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:78.0) Gecko/20100101 Firefox/78.0)
2020-12-14 17:59:34 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from ubnt (192.168.1.1) (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:78.0) Gecko/20100101 Firefox/78.0)
2020-12-14 17:59:40 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from ubnt (192.168.1.1) (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:78.0) Gecko/20100101 Firefox/78.0)
2020-12-14 18:03:49 ERROR (stream_worker) [libav.rtsp] RTP: PT=23: bad cseq 27c4 expected=1558
2020-12-14 18:03:51 ERROR (stream_worker) [libav.rtsp] RTP: PT=23: bad cseq 5b78 expected=2f49
2020-12-14 18:03:52 ERROR (stream_worker) [libav.rtsp] RTP: PT=23: bad cseq 8c94 expected=5ea1
2020-12-14 18:04:26 ERROR (stream_worker) [libav.rtsp] RTP: PT=23: bad cseq e7a8 expected=d45f
2020-12-14 18:04:28 ERROR (stream_worker) [libav.rtsp] RTP: PT=23: bad cseq ce72 expected=c17d
2020-12-14 18:11:26 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from ubnt (192.168.1.1) (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:78.0) Gecko/20100101 Firefox/78.0)
2020-12-14 19:48:45 ERROR (stream_worker) [libav.rtsp] RTP: PT=23: bad cseq 242f expected=0aa2
2020-12-15 02:32:57 ERROR (stream_worker) [libav.rtsp] RTP: PT=23: bad cseq 1c40 expected=0514
2020-12-15 02:33:00 ERROR (stream_worker) [libav.rtsp] RTP: PT=23: bad cseq 3fe1 expected=2887
```
Some errors but nothing related to my case.

And the Supervisor one : 
```
20-12-14 22:36:12 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
20-12-14 22:36:34 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
20-12-14 22:37:31 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-14 22:37:32 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-14 22:38:32 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
20-12-14 22:38:32 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
20-12-14 22:38:32 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
20-12-14 22:38:34 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
20-12-14 23:56:49 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
20-12-14 23:56:49 INFO (MainThread) [supervisor.resolution.check] System checks complete
20-12-15 01:46:13 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-15 01:53:01 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
20-12-15 01:53:01 INFO (MainThread) [supervisor.resolution.check] System checks complete
20-12-15 02:04:20 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
20-12-15 02:12:59 INFO (MainThread) [supervisor.host.info] Updating local host information
20-12-15 02:13:04 INFO (MainThread) [supervisor.host.services] Updating service information
20-12-15 02:13:05 INFO (MainThread) [supervisor.host.network] Updating local network information
20-12-15 02:14:04 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
20-12-15 02:14:04 INFO (MainThread) [supervisor.host] Host information reload completed
20-12-15 03:56:11 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
20-12-15 03:56:11 INFO (MainThread) [supervisor.resolution.check] System checks complete
20-12-15 04:10:44 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/vkorn/hassio-addons repository
20-12-15 04:10:44 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
20-12-15 04:10:44 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-12-15 04:11:10 INFO (MainThread) [supervisor.store] Loading add-ons from store: 71 all - 0 new - 0 remove
20-12-15 04:11:10 INFO (MainThread) [supervisor.store] Loading add-ons from store: 71 all - 0 new - 0 remove
20-12-15 05:34:26 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 257:None is not str
20-12-15 05:34:26 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
20-12-15 05:34:46 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-15 05:34:46 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
20-12-15 05:34:46 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
20-12-15 05:34:47 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
20-12-15 06:01:42 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
20-12-15 06:01:42 INFO (MainThread) [supervisor.resolution.check] System checks complete
20-12-15 06:13:12 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
20-12-15 06:39:10 INFO (MainThread) [supervisor.host.info] Updating local host information
20-12-15 06:39:14 INFO (MainThread) [supervisor.host.services] Updating service information
20-12-15 06:39:16 INFO (MainThread) [supervisor.host.network] Updating local network information
20-12-15 06:40:07 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
20-12-15 06:40:07 INFO (MainThread) [supervisor.host] Host information reload completed
20-12-15 08:08:46 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
20-12-15 08:08:46 INFO (MainThread) [supervisor.resolution.check] System checks complete
```

**Comment by postlund** [comment]
Is the `lock` entity present and working as expected, e.g. change state properly? How are you calling the `lock` service?

**Comment by Vartkat** [comment]
Yes it works when I lock or unlock it from the slave HA , the error is only fired on the Master.

**Comment by Vartkat** [comment]
I've got some new infos :  there's no lock service of the master !
<img width="468" alt="image" src="https://user-images.githubusercontent.com/1696899/102702920-7dd3da00-4268-11eb-87b4-866d52ba410a.png">

even if the lock domain is there : 
<img width="265" alt="image" src="https://user-images.githubusercontent.com/1696899/102702928-93490400-4268-11eb-97b8-96cd8455f6f3.png">

using Open ZWave beta. How is this possible ?

**Comment by postlund** [comment]
You need to add `lock:` to your config or use the `load_components:` if you run from master (as that is not in any release yet).

**Comment by postlund** [comment]
Did you get a chance to try what I wrote?

**Comment by gilperme** [comment]
@postlund I ran into this issue as well and loading the component, did the trick. Thank you!

**Comment by Vartkat** [comment]
I'm still getting some problems : 
 - I can unlock the remote lock but
 - state does not change on the master (I click on unlock, if I look the slave, the lock is unlocked, on the master the button remains 'Unlock')
 - I can't lock from the Master lovelace UI

What is strange is that I can lock and unlock from the Service panel on the Master.
The lovelace card I'm using is a standard entity card : 

```
type: entities
entities:
  - entity: switch.cabs_switch_cabin3
    name: Front Cabin 3
  - entity: lock.cabs_be468_touchscreen_deadbolt_locked_c3b
    name: Back
  - entity: lock.cabs_be469zp_connect_smart_deadbolt_locked_c3f
    name: Front
state_color: true
```

Seems I missed subscribing to an event even if I got all the default ones 
<img width="669" alt="image" src="https://user-images.githubusercontent.com/1696899/103150813-f1e61480-4777-11eb-8cdd-e31142187be3.png">

I was wondering, how does the yaml lines are working with the checkboxes in the Integrations panel ? Who has priority, is yaml the old manner and the Integration the new one ?
Do we need to comment most of the yaml if we use the integration ?

**Comment by postlund** [comment]
I @see your problem, you have entered all events on a single line or something. Can you provide your config here?

**Comment by Vartkat** [comment]
I didn't change my config since post1 : 
remote_homeassistant:```

  instances:
  - host: 192.168.1.249
    port: 8123
    access_token: !secret access_token
    entity_prefix: cabs_
    subscribe_events:
      state_changed
        - service_registered
        - zwave.network_ready
        - zwave.node_event
    include:
      domains:
      - sensor
      - switch
      - zwave
      - lock
      - climate
      entities:
      - binary_sensor.rpi_power_status
```

**Comment by Vartkat** [comment]
> You need to add `lock:` to your config or use the `load_components:` if you run from master (as that is not in any release yet).

nothing changed after lock: added.

I'm still wondering why my Master interface doesn't send the lock command. Cause if I do it manually from the master's dev tools, calling the lock.lock service works. But during all this nothing changes on the Interface, the button says Unlock at the begining, stays Unlock even if the lock is unlocked on salve, and remains Unlock when I reloack it from the dev tools.

**Comment by Vartkat** [comment]
That was this one : 
![image](https://user-images.githubusercontent.com/1696899/103378931-496fe180-4ae4-11eb-89d4-4a89a899712c.png)

Don't know where it comes from, perhaps because the setup in the Configuration.yaml was remaining after the release where one can do it from the Integration page.
Now it works, seems a bit slow to me, it takes 10 sec to reflect state of a lock on the master when it takes between 3 or 4 sec from the slave (wich is directly the one managing the lock) means there's a delay of 6 to 7 sec. Can this be reduced ?

**Comment by postlund** [comment]
Yeah, must have been imported weirdly or something. Hard to tell now. But you did what I was going to propose as solution. You don't have to include `state_changed` and `service_registered` anymore if you run from master, they are handled separately now.

There should not be any significant delays I would say, not sure why that would happen. You could try opening the Developer Tools on the main instance, pick Events and listen for state_changed events. Then try locking or unlocking, hopefully the event should appear quite instantly. If it's delayed, we can continue debugging from there.

**Comment by Vartkat** [comment]
As I don't know how to listen to multiple events and filter them I've done it on Node Red  : 
just for ref  the node : 
`[{"id":"7296660b.84a7f8","type":"server-events","z":"e837369c.48adc8","name":"","server":"dd1239cd.734838","event_type":"state_changed","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"waitForRunning":true,"x":140,"y":200,"wires":[["f8d52b4.1705a58"]]},{"id":"10766a20.d1b02e","type":"server-events","z":"e837369c.48adc8","name":"","server":"dd1239cd.734838","event_type":"call_service","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"waitForRunning":true,"x":110,"y":300,"wires":[["229ff9d0.e122b6"]]},{"id":"f8d52b4.1705a58","type":"switch","z":"e837369c.48adc8","name":"","property":"payload.entity_id","propertyType":"msg","rules":[{"t":"cont","v":"lock","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":110,"y":260,"wires":[["978d0e63.b6c528"]]},{"id":"229ff9d0.e122b6","type":"switch","z":"e837369c.48adc8","name":"","property":"payload.event.domain","propertyType":"msg","rules":[{"t":"cont","v":"lock","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":270,"y":300,"wires":[["978d0e63.b6c528"]]},{"id":"978d0e63.b6c528","type":"debug","z":"e837369c.48adc8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":450,"y":280,"wires":[]},{"id":"dd1239cd.734838","type":"server","name":"Home Assistant","legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]`

I don't know what you consider instantaneous but here are the results : 
2020-12-30T23:05:53.759683+00:00 <- Call service 
2020-12-30T23:05:56.577827+00:00  <- State changed
Almost 3 sec

2020-12-30T23:06:10.494865+00:00 
2020-12-30T23:06:13.742542+00:00
more than 3 sec

2020-12-30T23:06:23.284913+00:00
2020-12-30T23:06:26.740679+00:00
more than 3 sec

That's getting better the mote I play with it.

I did the same on the slave to compare : 
2020-12-30T23:14:18.306106+00:00
2020-12-30T23:14:21.272555+00:00
almost 3 sec

2020-12-30T23:16:08.181513+00:00
2020-12-30T23:16:10.943881+00:00
Less than 3 sec

2020-12-30T23:16:56.199349+00:00
2020-12-30T23:16:59.144435+00:00
A bit less than 3 sec

So, considering thers's Node Red and IP communication involved, we can say that's the same on the slave and the master, so it's not a question of remote_homeassistant but certainly a question of ZWave communication.

In both cases, the call-service is instantaneous.

Thanks for your help
