### ISSUE TITLE
Move repo to github.com/custom-components

### ISSUE THREAD

**Issue by lukas-hetzenecker** [custom-components/remote_homeassistant#95]
@postlund - as you've done more for this project in the previous weeks, than I've done in the previous years, I'd like to ask you if you also officially want to become a maintainer? :-) 
You've probably noticed that I barely have enough time to review the pull requests, and as I don't want to hold back these important and useful features, I suggest that you simply merge them yourself.

I'll also try to get this project moved to github.com/custom-components/remote_homeassistant so it's in a more neutral space (and hope this won't break the HACS integration)

And a big thank you for all the amazing work you did! 🥳 🎉

**Comment by postlund** [comment]
Sure, if you want to get it off your hands, I can take over 😉

I think old references are kept when doing a transfer, so current paths should work as well until it can be changed in HACS. We're in the same boat with localtuya as I'm about to take over that project as well. Let's see how it goes...

**Comment by lukas-hetzenecker** [comment]
> Sure, if you want to get it off your hands, I can take over 😉

The truth is currently I don't have enough time to keep up with all the bug reports. And personally I've moved most of my stuff to ozw and zigbee2mqtt, so I only need this component for a small corner-case in my home-assistant infrastructure.

Still plan on eventually getting to do some development for this component again, but this will be irregularly at best..

Anyway, I've pinged Ludeeus to check if it's possible to move the repo over :-)

> I think old references are kept when doing a transfer, so current paths should work as well until it can be changed in HACS

Sounds good. I thought it would still work after moving the project over, I'm just not sure what happens when the reference in the HACS repo also gets updated (if then e.g. a reinstallation is required).

> Let's see how it goes...

Good luck! 🍀

**Comment by lukas-hetzenecker** [comment]
Already got access to the @custom-components organization, trying to figure out the best course of action now.. 😅 
It would probably be best to first rename the repo to remote_homeassistant, and then Transfer ownership to @custom-components. 
Oh, and probably somehow request access for you as well? - Or are you already a member of custom-components because of localtuya?

**Comment by postlund** [comment]
I don't have access to it, so if you figure that out it would be great 😅 I might even suggest that we do the same thing with localtuya instead of moving it to my account.

**Comment by lukas-hetzenecker** [comment]
I'll give that a try now.. 🤞

**Comment by lukas-hetzenecker** [comment]
@postlund - seems to have worked.
Old links are still working, HACS still shows the versions/releases.
Just looks like I can no longer manage the project permissions, so I don't know if you still have access (would have checked the migrate members option)?

**Comment by lukas-hetzenecker** [comment]
i've pinged @ludeeus  about the permissions ;)

**Comment by lukas-hetzenecker** [comment]
hacs/default#757 is finally merged :tada: - so this should be resolved
