### ISSUE TITLE
Multiple instances stopped working

### ISSUE THREAD

**Issue by huemcos** [custom-components/remote_homeassistant#96]
I have 3 remote instances and worked well with v2.x
After upgrading to 3.1, only one remote instance works. 
In my yaml code below, always the last one works. If I comment out, 2nd and 3rd instances, the first instance works. 

`remote_homeassistant:
  instances:
  - host: redacted ip
    entity_prefix: "ha02_"
    verify_ssl: false
    access_token: "redacted"
    exclude:
      entities:
      - zone.home
      
  - host: redacted ip
    entity_prefix: "ha03_"
    verify_ssl: false
    access_token: "redacted"
    exclude:
      entities:
      - zone.home
      
  - host: redacted ip
    entity_prefix: "ha04_"
    verify_ssl: false
    access_token: "redacted"
    exclude:
      entities:
      - zone.home`

**Comment by huemcos** [comment]
Also, I see no option to add a 2nd remote instance on the Integrations page.

**Comment by postlund** [comment]
Check the log, we can't draw any conclusions from this.

Just add a new integration to add a new instance.

**Comment by huemcos** [comment]
I created a new long-live token and tried manually adding a second instance on the Integrations page, got the error “Aborted. Already configured”

Also, the only log that I saw that is related to the plugin was:

2020-12-27 09:22:57 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for remote_homeassistant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

I see no other error/warning related to other instances.

**Comment by postlund** [comment]
That's odd. What's the version of the remote instances? Are they clones of each other, e.g. restored from the same backup?

**Comment by huemcos** [comment]
Primary and remote instances are still on v116. No they are not clones. 
Is there any way to clear the plugin's "database"? It seems the remote instances are still there and stuck in limbo and made the primary instance confused. 

I have uninstalled the plugin, created new tokens on all remote instances, but can only get one to work at a time. It's been solid for months until I upgraded to 3.1, which is really strange.

**Comment by huemcos** [comment]
@postlund 
I updated my remote instances to v2020.12.1 still did not work.

I reverted to version 2.3 of the plugin, now my remote instances are all back.

**Comment by postlund** [comment]
0.116 should be fine, must be at least 0.111 IIRC. Did you check under Configuration->Integrations? They should be listed there. YAML-config is imported to config entries (the internal database used when setting up via the UI for instance). Removing the YAML-config will not remove the config entries, that you will have to do manually

**Comment by huemcos** [comment]
I did check Configurations ->Integrations. There's only one entity listed. 
Downgraded to version 2.3 and works fine. Something in 3.1 is preventing the other remote instances from working, or could just be my server (primary instance).

**Comment by postlund** [comment]
Hmm, then you probably have some strange leftovers in `.storage/core.config_entries`, you should probably have a look. In order to use config entries, a unique id must be used to map the instance to a configuration. It is fetched from the remote instance via the REST API. In case this ID is the same for all your instances, it won't work (and that's why I asked if they are clones). It's stored in `.storage/core.uuid`, maybe you can look at those as well?

**Comment by huemcos** [comment]
I found one error just now after a reboot of my main server.... see below. Not sure it means but works now that I still have version 2.3

Logger: homeassistant.config_entries
Source: config_entries.py:216
First occurred: 2:36:21 PM (1 occurrences)
Last logged: 2:36:21 PM

Error importing platform config_flow from integration remote_homeassistant to set up remote_homeassistant configuration entry: No module named 'custom_components.remote_homeassistant.config_flow'

**Comment by cbuxton5200** [comment]
Just adding here that I have the same issue, it stopped working on 3.1 and reverting back to 2.3 makes it work again.  I will look at the .storage/core.config_entries

**Comment by jasonatepaint** [comment]
I had this same issue and was tipped off by mention of HA clones.  I resolved it by making sure each HA instance has a unique uuid in `./storage/core.uuid`.  Then restarted those remote instances and then restarted my main instance and everything showed up correctly. 

If this is your problem, you can use this: [online uuid generator](https://www.uuidgenerator.net/version4) to create a unique id.  Just remove the dashes before pasting in `core.uuid`.

**Comment by huemcos** [comment]
changing the core.uuid fixes it!
