### ISSUE TITLE
New repository in HACS? Error?

### ISSUE THREAD

**Issue by matata86** [custom-components/remote_homeassistant#97]
Hi, I've been using Remote HA for a long time. The latest version works great.

Now that it has appeared in HACS as a new repository?

When I choose to install and restart. Is it still appearing in HACS as a new repository?

What is it?

Thank you.
![3](https://user-images.githubusercontent.com/28623294/103310249-6ee2e980-4a17-11eb-82fe-f0004e129dae.png)
![2](https://user-images.githubusercontent.com/28623294/103310252-6f7b8000-4a17-11eb-8285-7c4da37f85f7.png)
![1](https://user-images.githubusercontent.com/28623294/103310253-6f7b8000-4a17-11eb-9c0b-386e5f366bdf.png)

**Comment by postlund** [comment]
It is moving to the community repositories, see #95. Probably because of that.

**Comment by matata86** [comment]
Ok.. but why this -> When I choose to install and restart. Is it still appearing in HACS as a new repository?

**Comment by postlund** [comment]
That is indeed a mystery. Can you remove it as custom repository and see what happens? Should not be needed.

**Comment by matata86** [comment]
If I remove custom reposity, so Remote Home Assistant is not in Add reposity list. See video.

After remove custom reposity and restart is custom reposity still in custom repositity. See image. Screenhot is after remove reposity and reboot.
![after_restart](https://user-images.githubusercontent.com/28623294/103315566-3696d780-4a26-11eb-8975-e955ed3c108c.png)

https://user-images.githubusercontent.com/28623294/103315571-37c80480-4a26-11eb-8b6f-fba593c58fc0.mp4

**Comment by jhein05** [comment]
> That is indeed a mystery. Can you remove it as custom repository and see what happens? Should not be needed.



> Ok.. but why this -> When I choose to install and restart. Is it still appearing in HACS as a new repository?

Same here.

**Comment by Golab** [comment]
Same for me

**Comment by lukas-hetzenecker** [comment]
I've opened a PR with HACS to update the location of the repo hacs/default#757
Hope this will resolve the issues

**Comment by cbuxton5200** [comment]
Just adding to this that I have the same issue, I cannot remove the custom repository location (it comes back after removal and restart) and in the HACS integrations page, Remote Home-Assistant is always listed as "new" even after I install and restart.

**Comment by henrikhjelm** [comment]
any news on this one ?

**Comment by Madelinot** [comment]
Same issues here.  I un-installed and re-installed a few times and it constantly shows up.

**Comment by sshalyminov** [comment]
Same for me.

**Comment by postlund** [comment]
This issue will not go away until the PR mentioned by @lukas-hetzenecker has been merged.

**Comment by lukas-hetzenecker** [comment]
Should be really close to being merged now.. :)

**Comment by henrikhjelm** [comment]
> Should be really close to being merged now.. :)

:) soon i hope

**Comment by daandav** [comment]
Any update on this? Untill this is fixed I still use a dev version with the remote_service feature, since that does not install through HACS. I also note that the information page in HACS is not consistent with the github page.

**Comment by lukas-hetzenecker** [comment]
hacs/default#757 is finally merged :tada: - so this should be resolved
