### ISSUE TITLE
Read-Only State of imported entities - Is this normal?

### ISSUE THREAD

**Issue by daphatty** [custom-components/remote_homeassistant#98]
I've been struggling with my remote entities being imported in a read-only state. According to HA, "This entity ("_entity.name_") does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail." 

While HA [documentation](https://www.home-assistant.io/faq/unique_id) claims this only prevents the editing of the _**entity_id**_ and the _**friendly name**_, I have found additional limitations that apply within the remote_homeassistant context. These include,

On the primary/master instance,

- Remote entities cannot be Assigned to an Area
- Remote entities cannot be chosen as devices within an Automation, Scene, or Script.

So far, I've been unable to find additional information regarding this read-only state and am beginning to wonder whether this behavior is actually the expected behavior or if I've somehow misconfigured my remote_homeassistant instance. 

I am currently running remote_homeassistant v3.1 on Home Assistant Supervised version 2012.12.1 and HassOS 5.8. Remote_homeassistant was installed via HACS and configured through the UI with the Secure and Verify SSL options _not_ selected.

**Comment by postlund** [comment]
This is expected. For any of those features to work, the entity must exist in the entity registry and it's not an easy task to accomplish that. It also opens for a few other things to deal with, e.g. making it possible to change the entity id on the main instance. This would mean that an entity can have one entity id on the main instance and another one on the remote side, requiring some translation to be done. As I don't have the details, it likely also pulls in other things hidden under the surface. I intend to try to implement this at some stage, but probably not near time.

**Comment by daphatty** [comment]
Thanks, @postlund, for the clarification. I took the liberty to submit a pull request which adds this information to the Special Notes section of the Readme file. Hopefully the addition will save others some time.

**Comment by dbroome1978** [comment]
So in order to be able to control the lights, we also need to manually add them to the event registry?

**Comment by genebean** [comment]
I'm a little confused too... does this mean lights and media players on the remote instance can't have their state changed from the primary ha?

**Comment by genebean** [comment]
Thanks @daphatty, I appreciate the information.

**Comment by postlund** [comment]
@dbroome1978 You Can still control lights (or any other entity) via entity_id. You cannot use device triggers or similar as that requires the entity being added to the entity register and linked to a device in the device register.

@daphatty Did you open it towards this repository or your own clone? And as mentioned above, you can still control entities via automaton on the master "old style" via entity_id. It's not possible to use the new fancy features however.

@genebean All state changes are propagated to the master instance no matter what triggered the change (or where). If it's not updated then it's a bug or misconfiguration.

**Comment by genebean** [comment]
Thanks @postlund. My goal is to be able to control media players and lights via cards in the GUI on the master and to trigger presence based automations from the master when I enter the zone of the remote instance. Are you saying those things should all work?

**Comment by postlund** [comment]
@genebean I don't see any reason why that wouldn't work. Artwork will not work for media players though, see #48.

**Comment by daphatty** [comment]
@postlund - Thanks for the feedback. I can definitely see my remote devices populating within Automations on the primary HA instance (see below), but my use case also requires access to Device Triggers which make Automations far more useful IMHO.

![image](https://user-images.githubusercontent.com/28716334/104821067-26d10e80-57ee-11eb-9c12-cb2c3e118f57.png)

Ultimately, I may have to rethink my approach. Maybe I'll resort to using Node Red to bridge the Automation gap whilst leveraging Remote Home Assistant to keep things separate.

**Comment by postlund** [comment]
@daphatty Yes, device triggers won't work as it is now and maybe never will. I haven't looked into how those actually work, so I can't tell for sure though.
