### ISSUE TITLE
Remote updates shown only after reload

### ISSUE THREAD

**Issue by embcla** [custom-components/remote_homeassistant#99]
Hello and happy new year!

I am new to remote so forgive me if there is something not clear for me.
My need is to allow for second zwave and zigbee controllers far away from my primary ones to transmit information (receive not strictly needed but good to have, still have to figure out the workarounds).

So right now my remote is a PI4 with a conbee 2 stick and a couple sensors hooked up.
What I notice is that in my master there is no update (or it takes way too long, like more than 8h) unless I forcibly reload the integration.
Logs don't show anything related to remote and I didn't find a way to enable debug logging.

What can I do to fix this?

**Comment by postlund** [comment]
Please provide which version you installed and how you set it up.

**Comment by embcla** [comment]
I installed via HACS, v3.1
configured via UI to mirror binary and sensors, also explicitly selected which entities to consider

Can't find a way to copy the configuration, it's not explicitly written anywhere

**Comment by postlund** [comment]
Try upgrading to 3.2 released yesterday, it should hopefully solve the problem.

**Comment by embcla** [comment]
![image](https://user-images.githubusercontent.com/54371771/103411024-3c97d000-4b6e-11eb-9d86-5d80a8548d62.png)

3.2 doesn't show, is it "master" ?

**Comment by viper1978** [comment]
I have exactly the same problem.
Main: Home Assistant OS 5.9 running on ESXi
Slave: Home Assistant OS 5.9 running on raspberry pi 3b

The pi is used as a bluetooth tracker. The pi updates like it should with constantly changing rssi values.
However on the main the values are only updated on a complete restart or after a force reload of the remote_homassistant component.

I installed the 3.1 version of the component, the 3.2 version I don't see.

**Comment by embcla** [comment]
@viper1978 
Honestly I ended up moving to zigbee2mqtt and zwave2mqtt, they work flawlessly.ù

@postlund 
There still is no 3.2 available anywhere, also not here on github

**Comment by postlund** [comment]
@embcla Think we need https://github.com/hacs/default/pull/757 merged to have it fixed. I'll see if Lukas can fix the issues.

**Comment by clau-bucur** [comment]
Exactly the same situation as @viper1978.
I have some additional BLE climate entities on the slave which I need forwarded to the master. They don't update the state neither.

**Comment by danmed** [comment]
Same problem with zigbee devices.. needs to be given a kick to update.

**Comment by felipealmeida** [comment]
Isn't this because state_changed event is not being subscribed? I just learnt that this was required by looking at the example in the README.md

**Comment by felipealmeida** [comment]
I think state_changed should be added to the config_flow UI as a warning

**Comment by postlund** [comment]
`state_changed` and `service_registered` must be subscribed to manually when running latest released version. This has been fixed on `master` (so you never have to specify these) and  will be part of next release. But if you pick `master` it should work fine.

**Comment by DRracer** [comment]
@postlund thank you for your comment, manually registering these `state_changed` and `service_registered` solved this issue on my installation (ARM cortex-a7, python 3.9).

**Comment by iKingRPG** [comment]
in hacs version i couldnt get 3.2 either, so I selected "master" and it seems to be fixed now.

**Comment by c3reeman** [comment]
Having the exact same problem here, the initial import of entities is good but then they don’t update, I’ve tried 3.1 & master tried going through integrations and entering manually in the yaml with no success.

I’m  trying to import Bluetooth temperatures but I’ve noticed any kind of entity responds in the same way

**Comment by danmed** [comment]
> Having the exact same problem here, the initial import of entities is good but then they don’t update, I’ve tried 3.1 & master tried going through integrations and entering manually in the yaml with no success.
> 
> I’m trying to import Bluetooth temperatures but I’ve noticed any kind of entity responds in the same way

https://github.com/custom-components/remote_homeassistant/issues/99#issuecomment-756421747

**Comment by embcla** [comment]
If I may suggest, anyone looking to have more than one instance of HA should drop the remote integration and go MQTT instead.

I've successfully setup a Rpi as a secondary instance with zigbee2mqtt and zwavejs2mqtt both publishing to the master broker and it's been (decently) reliable. A beefier machine would handle all the messaging and container stuff much better than the Pi. 
Adding, removing and configuring must be done from the Pi, but once that's done, any entity becomes fully integrated in the master instance, available for templates, automation and whatnot

**Comment by pro2call-nl** [comment]
> > Having the exact same problem here, the initial import of entities is good but then they don’t update, I’ve tried 3.1 & master tried going through integrations and entering manually in the yaml with no success.
> > I’m trying to import Bluetooth temperatures but I’ve noticed any kind of entity responds in the same way
> 
> [#99 (comment)](https://github.com/custom-components/remote_homeassistant/issues/99#issuecomment-756421747)

same problem here. i have 1 HA running in the garden to get my miflora sensor data. on that pi it is OK. but on the "master" its not updating only after an restart

**Comment by embcla** [comment]
I tried this again yesterday.
Using the configuration yaml, with the right events subscriptions, and still nothing happens.

I honestly have no idea what else to try here, for me it's definitely broken.

**Comment by postlund** [comment]
Please try with the latest release (3.2 or later) in HACS.

**Comment by postlund** [comment]
Try upgrading to the latest release (and you can also remove `state_changed` and `service_registered` now). Hopefully it works better.
